distributor:
    dataProviders:
        password:
            alphabets:
                9cf4dc54-9119-4b7f-9798-e988f880f35e:
                    uuid: 9cf4dc54-9119-4b7f-9798-e988f880f35e
                    weight: 10000
                    value:
                        alphabet: abcdefghijklmnopqrstuvwxyz
                        min: 0
                db17e609-90aa-4092-b744-2f505c4d0ce1:
                    uuid: db17e609-90aa-4092-b744-2f505c4d0ce1
                    weight: 10100
                    value:
                        alphabet: ABCDEFGHIJKLMNOPQRSTUVWXYZ
                        min: 0
                982bf9f8-efef-4adf-8bb0-533881dffbe8:
                    uuid: 982bf9f8-efef-4adf-8bb0-533881dffbe8
                    weight: 10200
                    value:
                        alphabet: '0123456789'
                        min: 0
                bba47ea6-9ac1-47a3-bc93-1ea79ec84fb1:
                    uuid: bba47ea6-9ac1-47a3-bc93-1ea79ec84fb1
                    weight: 10300
                    value:
                        alphabet: '!#%&/(){}[]+-'
                        min: 0
metaData:
    name: Password Provider
    version:
        core: 1.0.0
        distributor-core: 1.0.0
        distributor-password-provider: 1.0.0
    includes: {  }
